<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\tModLoader.targets"/>
    <PropertyGroup>
        <AssemblyName>SubworldLibraryCommunityFork</AssemblyName>
        <RootNamespace>SubworldLibraryCommunityFork</RootNamespace>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="ModCallExample/**/*.cs"/>
        <Compile Remove="ModCallExample/**"/>
    </ItemGroup>
</Project>
